### ISSUE TITLE
Answer hash

### ISSUE THREAD

**Issue by mrWodoo** [mousey/FIFA13-Ultimate-Team-Search#2]
I have to use your 'eahashor'? MD function? If so then this doesn't work for me... always error msg with 'Answers do not match for nucleus id xxxxx'

**Comment by nullablebool** [comment]
Use the JavaScript file, ea/hash.js - this one works correctly. Notice it's not a true MD5 hash.

**Comment by mousey** [comment]
I will look at eahashor, I think I uploaded a testing version of it.

**Comment by mousey** [comment]
I've rewritten EAHashor to now work

**Comment by cluber22** [comment]
Has EA changed it hashing algorithm again? Your EAHashor class appears to give me a different hash than the EA server for the name answer. Could someone please confirm this?

**Comment by samdoidge** [comment]
Yes it seems so - I've taken the posted hash value when submitting the secret question in my browser and hardcoded in. But I'm sure the javascript hashing algorithm could be copied down into the function again.

**Comment by cluber22** [comment]
I've just tested the original javascript code, nothing seems to have changed in EA's algorithm that I can see, I just compared http://jsfiddle.net/cluber22/pdpv3/ with the EAHashor and it indeed gives two different hashes. EA's algorithm can be found at http://cdn.easf.www.easports.com/uk/football/static/js/bundle/easf_en_GB!fifa-ultimate-team.app.js around line 2000.

In addition, 'test' = 6337a43e8cd36058e80ae8cb4f465998 (javascript side) But the PHP script doesn't get this.

**Comment by nullablebool** [comment]
Are you sure? Here is EA's:

http://jsfiddle.net/mTKv4/

I get the same result.

**Comment by nullablebool** [comment]
Are you sure? Here is a jsfiddle with EA's code, and I get the same result:

http://jsfiddle.net/mTKv4/

**Comment by cluber22** [comment]
reopen?

**Comment by cluber22** [comment]
If anyone is interested I have wrote the hashing algorithm in Python. https://github.com/cluber22/UltimateTeamBot/blob/master/EAHashingAlgorithm.py

**Comment by samdoidge** [comment]
Awesome work @cluber22, gives correct value for me. I've added acceptance of a command line argument on [my fork](https://github.com/samdoidge/UltimateTeamBot) for the secret string - so for integration with php, I see `exec('python hashfile secret');` as a way - not sure if there is a better method.

**Comment by cluber22** [comment]
As far as a PHP implementation goes that seems the best temporary solution until the PHP class can be fixed.
