### ISSUE TITLE
Does login still work?

### ISSUE THREAD

**Issue by samdoidge** [mousey/FIFA13-Ultimate-Team-Search#6]
Just trying this..

$EASF_SESS returns 'close' for me.

and I recieve the following on searching:

```
{"message":null,"reason":"expired session","code":401} 
```

But I do get a NUC and it does seem to return my in game username when looking at $EALOGIN

**Comment by hamishtaplin** [comment]
Just started looking at this and having the same problem. Any ideas?

**Comment by samdoidge** [comment]
FIFA seem to have changed the hash algorithm again - for me I've copied the posted hash value when submitting my secret question from the browser and hardcoded this in. The location connector.php expects certain values to be may have also changed (I've changed a few things to get working - let me know if you still can't connect and I'll submit a pull request)

**Comment by hamishtaplin** [comment]
That would be most helpful, I wouldn't know where to start.

How did you get your hash? Fiddler or something?

**Comment by samdoidge** [comment]
I used Firebug extension with Firefox to look at the Post data and get the hash. 

I've forked someone else's fork as it had example login. Have added updates to that: https://github.com/samdoidge/FIFA13-Ultimate-Team-Search if you want to clone, should just need your details and the hash in `login_and_first_search.php` file to have it working.

**Comment by hamishtaplin** [comment]
Yeah working great now.

**Comment by SohelMansuri** [comment]
Okay SamDoidge, I sent you an email before. 

After reading your issues and solutions, I recently got the log in to work.  

My Questions:
What do you use to monitor http traffic? For example, Firebug (How do you use this?)
Have you used the FUTClient.java file? If so, how would I structure my ini file?

How would I use firebug to figure out different parameters that are used in the searchor.php searchplayer method?

Thanks,

**Comment by SohelMansuri** [comment]
Hey Samdoidge, this is me.

I recently got the login to work.   However, I am having issues understanding the code.

My Questions:
How do I intercept the http traffic? (If I use Firefox, where do I begin?)
Have you tried FUTClient.java? If so, can u show me an example of the required ini File?

Thanks,

**Comment by SohelMansuri** [comment]
Hey Samdoidge, this is me.

I recently got the login to work.   However, I am having issues understanding the code.

My Questions:
How do I intercept the http traffic? (If I use Firefox, where do I begin?)
Have you tried FUTClient.java? If so, can u show me an example of the required ini File?

Thanks,

**Comment by SohelMansuri** [comment]
I'm sorry if I put more than 1 comment. I don't see it so I didn't know if it was submitted or not.

**Comment by robsn** [comment]
Hi, does anyone know who to handle the new login? it's redirecting but my login request won't follow instead returns an 200 and closes connection.

**Comment by SohelMansuri** [comment]
I got the login to work on PHP but can't figure out what is wrong with the
JAVA code.

Which code are you working in?

**Comment by curt2008** [comment]
https://github.com/curt2008/Fifa13-Ultimate-Team-PHP-App - all working well and great, constantly updated

**Comment by SohelMansuri** [comment]
Hey,

In your functionor.php file, under your cardtype() function, should case 3
or 5 be TOTW instead of both being TOTY?

Thanks,

**Comment by SohelMansuri** [comment]
I mean case 5 or 6...

**Comment by samdoidge** [comment]
@curt2008 - Couldn't connect when I tried your repo.    

> [reason] => expired session [code] => 401 

I'm thinking hash has changed again, but haven't had time to look into

**Comment by cluber22** [comment]
My app is still working with no changes so i'm guessing hash hasn't changed?

**Comment by curt2008** [comment]
My current repo only works with Xbox, I'll attach information on how to change it to PS3 shortly

**Comment by samdoidge** [comment]
@cluber22 you are using the [python hashing version you wrote](https://github.com/samdoidge/UltimateTeamBot/blob/master/EAHashingAlgorithm.py) correct? That does still work - and gives a different value to the one attached in @curt2008's repo. 

@curt2008 I changed the connector to work for PS3, but the hash value returned wasn't letting me in. Using the hashing function in the previous link works.

I've updated [my fork](https://github.com/samdoidge/FIFA13-Ultimate-Team-Search) of this repo to include your referrer addition (nice work) and array position changes. @cluber22 I also included your python hash function in the fork

**Comment by curt2008** [comment]
@samdoidge just to notify you when using your connector it will no longer work with Xbox accounts, i'll update my file so it can work with both shortly.

**Comment by samdoidge** [comment]
@curt2008 Yeah true, I did add in the readme, but if someone misses: ps3 only at moment,`$machine = $d->shardInfo[1]->customdata1[1];` would need changing

**Comment by samdoidge** [comment]
Closing due to age.
